{
    "name": "next-auth-jest-error",
    "version": "0.1.0",
    "scripts": {
        "dev": "next dev",
        "test": "jest"
    },
    "dependencies": {
        "next": "13.4.16",
        "next-auth": "4.23.0",
        "react": "18.2.0",
        "react-dom": "18.2.0",
        "react-i18next": "13.1.2"
    },
    "devDependencies": {
        "@babel/core": "7.22.10",
        "@babel/preset-env": "7.22.10",
        "@babel/runtime": "7.22.10",
        "@testing-library/dom": "9.3.1",
        "@testing-library/jest-dom": "6.0.0",
        "@testing-library/react": "14.0.0",
        "@testing-library/user-event": "14.4.3",
        "@types/jest": "29.5.3",
        "@types/node": "18.17.5",
        "@types/react": "18.2.20",
        "@types/react-test-renderer": "18.0.0",
        "@types/testing-library__jest-dom": "5.14.9",
        "babel-jest": "29.6.2",
        "jest": "29.6.2",
        "jest-environment-jsdom": "29.6.2",
        "jest-fetch-mock": "3.0.3",
        "jest-mock": "29.6.2",
        "next-router-mock": "0.9.9",
        "react-test-renderer": "18.2.0",
        "ts-node": "10.9.1",
        "typescript": "5.1.6"
    },
    "packageManager": "yarn@3.6.1"
}
